capability:
  description: SQLite database access via MCP
  domains:
  - databases
  features: &id001
  - sqlite
classification:
  security_audit: '2025-08-06T23:15:43.468271'
  trust_level: community
economics:
  credit_cost:
    base: 3
    per_call: 0.1
    per_second: 0.05
  value_score: 0.5
evolution:
  improvement_suggestions: []
  last_improved: null
  parent_version: null
  performance_score: 0.0
  usage_count: 0
execution:
  container: cogplan/tool-runtime:2.0
  isolation: required
  resources:
    cpu: 0.5
    memory: 512MB
    network: restricted
    timeout: 30
identity:
  family: evolution/uncategorized
  name: sqlite
  uuid: cogplan-tool-2025-08-06-sqlite
  version: 1.0.0
interface:
  inputs:
  - constraints:
      read_only: true
    id: query
    required: true
    type: sql
  outputs:
    type: any
origin:
  adaptation_date: '2025-08-06T23:15:43.465623'
  discovered_by: tool_hunter_agent
  discovered_from: https://github.com/modelcontextprotocol/servers/sqlite
  original_protocol: mcp
protocol:
  mcp_config:
    resources:
    - sqlite
    server: sqlite-server
    tools: *id001
  type: mcp
