# Credit Sentinel v2 Configuration
# Real-time token and wall-time throttling

# Global credit limit for entire system
global_hard_cap: 1000

# Credits between checkpoints
checkpoint_interval: 50

# Maximum wall time in milliseconds (2 minutes)
max_wall_time_ms: 120000

# Per-agent credit soft caps
agent_caps:
  planner: 50
  codegen: 150
  backend-tester: 200
  frontend-tester: 150
  image-agent: 100
  integration-agent: 120
  tool-builder: 180
  credit-sentinel: 40
  meta-analyst-v2: 120
  semantic-diff-agent: 60
  risk-ledger-agent: 80
  sla-verifier: 120
  stress-tester: 150
  ui-journey-recorder: 100

# Wall-time limits per agent/tool (milliseconds)
wall_time_limits:
  default: 45000          # 45 seconds default
  container_runner: 60000  # 60 seconds for Docker
  stress-tester: 120000    # 2 minutes for load tests
  ui-journey-recorder: 90000  # 90 seconds for browser automation
  tool-builder: 60000      # 60 seconds for tool creation

# Throttle thresholds (percentage of soft cap)
throttle_thresholds:
  warn: 0.8      # 80% - start warning
  throttle: 0.9  # 90% - throttle operations
  abort: 1.0     # 100% - abort agent