name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-dev.txt || pip install ruff mypy bandit pytest pytest-cov pytest-xdist coverage pydeps graphviz jsonschema pytest-asyncio
      - run: ruff check .
      - run: mypy --strict .
      - run: python -m bandit -r .
      - run: pytest -n auto --cov=./ --cov-report=xml --cov-fail-under=90
